replicaCount: 1

image:
  repository: "homeassistant/home-assistant"
  pullPolicy: IfNotPresent
  tag: "2024.8.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "homeassistant"

podAnnotations: {}
podLabels:
  app: "homeassistant"
  home: "main"

podSecurityContext: {}

securityContext:
  privileged: true
  runAsUser: 0
  runAsGroup: 0

service:
  type: ClusterIP
  port: 8123

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 150m
    memory: 450Mi
  limits:
    cpu: 250m
    memory: 768Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

livenessProbe:
  httpGet:
    path: /api/
    port: 8123
    httpHeaders:
      - name: Authorization
        value: ""
  initialDelaySeconds: 15
  periodSeconds: 30
readinessProbe:
  tcpSocket:
    port: 8123
  initialDelaySeconds: 15
  periodSeconds: 30

volumeMounts:
  - name: config
    mountPath: /config
    readOnly: false

volumes: []

volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: nfs-csi
      resources:
        requests:
          storage: 5Gi

nodeSelector: {}

tolerations: {}

affinity: {}
